### ISSUE TITLE
**TypeError: Cannot read properties of undefined (reading 'token')**

### ISSUE THREAD

**Issue by fyflo** [qqquiu/dota2-webdraft#3]
Hello
Error

E:\obserber\dota2-webdraft-main>npm install   & node main.js

up to date, audited 85 packages in 600ms

8 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
Dota 2 GSI listening on port 3000
**TypeError: Cannot read properties of undefined (reading 'token')**
    at EventEmitter.<anonymous> (E:\obserber\dota2-webdraft-main\main.js:63:56)
    at EventEmitter.emit (node:events:518:28)
    at Check_client (E:\obserber\dota2-webdraft-main\node_modules\dota2-gsi\index.js:30:12)
    at Layer.handle [as handle_request] (E:\obserber\dota2-webdraft-main\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\obserber\dota2-webdraft-main\node_modules\express\lib\router\route.js:144:13)
    at E:\obserber\dota2-webdraft-main\node_modules\dota2-gsi\index.js:102:13
    at Layer.handle [as handle_request] (E:\obserber\dota2-webdraft-main\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\obserber\dota2-webdraft-main\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (E:\obserber\dota2-webdraft-main\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (E:\obserber\dota2-webdraft-main\node_modules\express\lib\router\layer.js:95:5)

**Comment by qqquiu** [comment]
Hi! The current code in this repository is very much experimental and there are almost no safe-guards in case the incorrect data is read from the gamestate at any time.

Aside from asking you to check if you followed all steps properly such as downloading the CFG file and adding the parameter to your Dota 2 launch options, you may try to run it after connecting to a replay and also immediatly restarting in cases of such failure. It's very unlikely I'll be able to return to this project to make it production-ready so please consider it a template for your personal implementation.

**Comment by fyflo** [comment]
Hello!
I substituted a new token and the necessary data appeared in cmd.
I'll try to finish it.
Thanks for the answer.

**Comment by fyflo** [comment]
If you have time, please look at this code, everything is correct.
Since after starting the server the browser cannot find [draft.html](url)

// Web framework + sockets
const express = require("express");
const express_app = express();
const http = require("http");
const http_server = http.createServer(express_app);
const { Server } = require("socket.io");
const io = new Server(http_server);

// Server
const path = require("path");
express_app.use(express.static("/public"));

express_app.get("/draft", (req, res) => {
  res.sendFile(path.join(__dirname + "/draft.html"));
});
![2024-05-29 13_02_38-](https://github.com/qqquiu/dota2-webdraft/assets/109218111/6cb839f1-aaca-48c3-94f6-41efcb7b0236)
